version: '3'

services:
  nextjs-app:
    container_name: nextjs-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
